name: ServerHelper
main: net.cyberflame.serverhelper.ServerHelperPlugin
version: ${project.version}
description: Various utilities
api-version: '1.20'
bootstrapper: net.cyberflame.serverhelper.ServerHelperBootstrap
loader: net.cyberflame.serverhelper.ServerHelperLoader
