name: ServerHelper
main: net.cyberflame.serverhelper.ServerHelperPlugin
version: ${project.version}
description: Various utilities
api-version: '1.21.4'
website: https://cyberfla.me/
author: CyberFlame (Aaron)
load: STARTUP
bootstrapper: net.cyberflame.serverhelper.ServerHelperBootstrap
loader: net.cyberflame.serverhelper.ServerHelperLoader
