name: ServerHelper
main: net.cyberflame.serverhelper.ServerHelperPlugin
version: 1.0
description: Utilities for the NCEA Help Minecraft server
api-version: '1.20'
bootstrapper: net.cyberflame.serverhelper.ServerHelperBootstrap
loader: net.cyberflame.serverhelper.ServerHelperLoader
