name: ServerHelper
main: net.cyberflame.serverhelper.Main
version: ${project.version}
description: Utilities for the NCEA Help Minecraft server
website: https://cyberfla.me/
author: CyberFlame (Aaron)
api-version: 1.18
load: STARTUP
commands:
  triggergc:
    aliases: [garbagecollect, gc]
    description: "Runs the garbage collector"
    permission: serverhelper.gc
  toggledebug:
    aliases: [debugalerts, debugnotifications, debugalertstoggle, dat, notify, alerts, notifications]
    description: "Toggles debug mode"
    permission: serverhelper.debug
  serverhelper:
    aliases: [sh]
    description: "Prints plugin information, and is the root command for subcommands"
    permission: serverhelper.main

permissions:
  serverhelper.gc:
    description: "Allows the user to run the garbage collector"
    default: op
  serverhelper.debug:
    description: "Allows the user to toggle debug mode"
    default: op
  serverhelper.main:
    description: "Allows the user to run the main command"
    default: true
  serverhelper.reload:
    description: "Allows the user to run the reload subcommand"
    default: op