name: ServerHelper
main: net.cyberflame.serverhelper.ServerHelperPlugin
version: ${project.version}
description: Various utilities
website: https://cyberfla.me/
author: CyberFlame (Aaron)
api-version: 1.20
load: STARTUP
