name: Submit dependencies
on:
  push:
    branches:
      - master # run the action on your projects default branch

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      
      - name: 'Set up Java'
        uses: actions/setup-java@v3
        with:
          distribution: 'semeru' # See 'Supported distributions' for available options
          java-version: '20'
          cache: 'maven'

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
